### PR TITLE
Convert to CMAKE build system and compile time override of R3D_MAX_VERTS

### PR DESCRIPTION
**Pull request by raovgarimella**
Converted R3D to use a modern CMake build system. You can use CMake to build the code, test it and install it (with appropriate CMake config files so other packages can import it easily). Some minor file location reorganization as top level directory was getting crowded. I tested the make, make test and make install options and verified that it was writing the correct stuff into the install dir. I also plopped it in as a submodule into Wonton and tested it with that.

Also, modified `r3d.h` to include `r3d-config.h` which has the R3D_MAX_VERTS definition. CMake will take a r3d-config.h.in as a template and fill the R3D_MAX_VERTS value. That value is set to 512 in the CMakeLists.txt file but can be overridden by a command line definition in the CMake command. I tested both default and custom settings.

I updated the Readme.md to reflect all this. So take a look.

Three last things:
1. Due to the autogenerated r3d-config.h file, you cannot use anything other than CMake to build the code - vanilla makefiles won't work
2. I will make a Spack recipe for R3D if you decide to accept these changes. Spack is a package manager from Livermore.
3. You may want to consider tagging the repo with version numbers

### CODE REVIEW

**Comment by raovgarimella** [comment]
@denissen-lanl Can you tag Daryl in a comment so he can see it and offer any suggestions/corrections?

**Comment by devonmpowell** [comment]
Thanks Rao,
Let me take a look at this and I'll merge next week (things are a bit chaotic here at the moment)
Devon

**Comment by devonmpowell** [comment]
Hmm, so I merged the PR and now there are conflicts. 
Would you mind taking a look?
Devon

**Comment by raovgarimella** [comment]
Devon, probably because the system didn't clean up the top level stuff (I moved code files into src to keep things clean). I will take a look why it went wrong.

**Comment by raovgarimella** [comment]
Devon, I think you mistakenly merged the dynamic array version of the code (PR 18) instead of merging (PR 19). You will have to roll master back.

**Comment by devonmpowell** [comment]
Ah shoot, you're right.
It should be good to go now.

**Comment by raovgarimella** [comment]
@devonmpowell  You may have to revert this as well because, I mistakenly rebased it on  your erroneously merged request. I will then update my PR and let you know when it is good to merge

**Comment by raovgarimella** [comment]
Maybe. I am back-to-back meetings. I will try to examine it as soon as possible and verify that everything is good.

**Comment by devonmpowell** [comment]
Thanks, let me know. Sorry for the confusion.

**Comment by raovgarimella** [comment]
@devonmpowell 
I believe you should revert master to this hash b3eef85ae (to undo the effect of merging #18 and #19). Then I will revert my CMake branch also and give you a clean PR.

(apologies if you know this already)
Note that some of the Stackoverflow answers on how to do this preserve the history of having made the merge and then reverting it. I believe we need to just clear out the mistakes without any need for history preservation. In that case, this is what I would do:

```
git reset --hard b3eef85ae
git push --force
```

This is borne out by the example in this stackoverflow post

https://stackoverflow.com/questions/2541545/is-there-a-difference-between-git-reset-hard-hash-and-git-checkout-hash/2541617#2541617

**Comment by devonmpowell** [comment]
@raovgarimella 
Okay, this is done. I had reset it the same way last time, but to the wrong commit apparently...

**Pull request merged**
